dist: xenial
sudo: required
language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: install
      name: "Install Web"
      script: ./scripts/install_web
    - name: "Install Native"
      script: ./scripts/install_native
    - stage: test
      name: "Test Web"
      script: ./scripts/test_web
    - name: "Test Native"
      script: ./scripts/test_native
    - stage: deploy
      name: "Deploy"
      script: ./scripts/deploy
stages:
  - install
  - test
  - name: deploy
    if: branch = master

# install:
#   - sudo pip install awscli
# before_script:
#   - npm install
#   # - npm test
# script:
#   - npm run build
# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   bucket: $S3_BUCKET
#   skip_cleanup: true
#   local-dir: public
#   acl: public_read
#   cache_control: "max-age=21600"
# after_success: 
# branches:
#   only:
#   - master
#   - develop
# before_deploy:
#   - aws s3 rm s3://$S3_BUCKET --recursive
# after_deploy:
# - aws configure set preview.cloudfront true
